name: example
description: Example app for stdnum_dart.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  stdnum_dart:
    path: ../
