name: stdnum_dart
description: Validate, compact, and format international tax, VAT, and personal
  identity document numbers in Dart.
version: 0.2.1
homepage: https://github.com/augustodia/stdnum-dart
repository: https://github.com/augustodia/stdnum-dart
issue_tracker: https://github.com/augustodia/stdnum-dart/issues
documentation: https://github.com/augustodia/stdnum-dart#readme

topics:
  - validation
  - documents
  - tax-id
  - identity
  - stdnum

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
